version: "3.7"

services:

  #Builds the frontend Docker image and creates the frontend microservice
  yolo-client:
    image: faska/yolo-client:v1.0.0
    build: ./client
    container_name: yolo-client
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    depends_on: 
      - yolo-backend
    networks:
      - app-net
    volumes:
      - my-own-volume:/app  

  #Builds the backend Docker image and creates the backend microservice
  yolo-backend:
    image: faska/yolo-backend:v1.0.0
    build: ./backend
    container_name: yolo-backend
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "5000:5000"
    depends_on: 
      - app-ip-mongo
    environment:
      MONGO_URL: mongodb://mongo:27017/mydatabase

    networks:
      - app-net
    volumes:
      - my-own-volume:/app    

  #Creates the database microservice
  app-ip-mongo:
    image: mongo
    container_name: app-mongo
    ports:
      - "27017:27017"
    networks:
      - app-net
    volumes:
      - my-own-volume:/app  

#Creates the network infrastructure necessary for the containers to communicate with each other
networks:
  app-net:
    name: app-net
    driver: bridge
    attachable: true
    ipam:
      config:
        - subnet: 172.20.0.0/16 
          ip_range: 172.20.0.0/16 

#Creates a Docker volume that persists all the data stored in the database
volumes:
  my-own-volume:
    driver: local





