apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: yolo-app
  labels:
    app: backend
    component: back
spec:
  type: LoadBalancer
  selector:
    app: backend
    component: back
  ports:
    - port: 5000
      protocol: TCP 
      targetPort: 5000
      nodePort: 30100  