apiVersion: v1
kind: Service
metadata:
  name: yolo-front
  namespace: yolo-app
  labels:
    app: yolo
    component: front
spec:
  type: LoadBalancer
  selector:
    app: yolo
    component: front
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      nnodePort: 30110